### ISSUE TITLE
How to run on Windows

### ISSUE THREAD

**Issue by dabbers** [harry5z/Sanguosha#1]
When I attempt to compile this on Windows, I see the following:

PS C:\Sanguosha-master> java .\src\net\server\Server.java
Error: Could not find or load main class .\src\net\server\Server.java

Any advice? I see that the public int main exists.  So not sure why it can't find it.

**Comment by harry5z** [comment]
Hi @dabbers, so I'm not actively working on this, as this is sorta a practice project for myself. Per your question, I think you need to compile all files under src together.

That said, I used eclipse as the IDE for this project and have never tried cmdline compiler. Hopefully this works.
